### ISSUE TITLE
issues with LoggingRole.pm

### ISSUE THREAD

**Issue by rbutleriii** [sanger-pathogens/Bio-RetrieveAssemblies#11]
When I try to execute with any species name or format type I get the same message, even with just "retrieve_assemblies Salmonella". Error message below:

$ retrieve_assemblies -a -f gff Sporogenes
All arguments to easy_init should be either an integer log level or a hash reference. at /usr/local/share/perl5/Bio/RetrieveAssemblies/LoggingRole.pm line 15.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 67.
Use of uninitialized value $columns[0] in string eq at /usr/local/share/perl5/Bio/RetrieveAssemblies/RemoteSpreadsheetRole.pm line 68.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.
Use of uninitialized value in string ne at /usr/local/share/perl5/Bio/RetrieveAssemblies/WGS.pm line 46.

**Comment by andrewjpage** [comment]
I'm afraid it looks like NCBI have overhauled their website for WGS assemblies, so this code is no longer working.  Its on our list (and many other peoples lists) to address this more general problem of getting data easily from NCBI and the ENA.
