### ISSUE TITLE
Add --verbose to print what is happening

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/Bio-RetrieveAssemblies#6]
Be great to have some STDERR output as it downloads etc so I know something is happening.

**Comment by andrewjpage** [comment]
I've added a verbose option (-v) which logs everything as it goes along.   From testing this, the NCBI server it connects to seems to crawl along at dialup speeds sometimes.  Its version 1.1.4 and will be available on cpan when its indexed.
